version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "GuruAPI"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-843p59v2f7ut"
s3_prefix = "GuruAPI"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
disable_rollback = true
