AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Guru Website Backend API
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs14.x
    Architectures:
      - x86_64

Resources:
  AddArtifact:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: aws/functions/add-artifact
      Handler: add-artifact-fn.handler
      FunctionName: Guru-Add-Artifact
      Description: AWS Lambda function for adding an artifact in the DB
      Layers:
        - !Ref GuruLayer
      Events:
        AddArtifactAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /artifact
            Method: post
  DelArtifact:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: aws/functions/del-artifact
      Handler: del-artifact-fn.handler
      FunctionName: Guru-Del-Artifact
      Description: AWS Lambda function for adding an deleting in the DB
      Layers:
        - !Ref GuruLayer
      Events:
        DelArtifactAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /artifact
            Method: delete
  GetArtifact:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: aws/functions/get-artifact
      Handler: get-artifact-fn.handler
      FunctionName: Guru-Get-Artifact
      Description: AWS Lambda function for fetching an artifact from the DB
      Layers:
        - !Ref GuruLayer
      Events:
        GetArtifactAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /artifact
            Method: get
  UpdArtifact:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: aws/functions/upd-artifact
      Handler: upd-artifact-fn.handler
      FunctionName: Guru-Upd-Artifact
      Description: AWS Lambda function for upding an artifact in the DB
      Layers:
        - !Ref GuruLayer
      Events:
        UpdArtifactAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /artifact
            Method: patch
  ScanArtifact:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: aws/functions/scan-artifact
      Handler: scan-artifact-fn.handler
      FunctionName: Guru-Scan-Artifact
      Description: AWS Lambda function for scanning artifacts in the DB
      Layers:
        - !Ref GuruLayer
      Events:
        ScanArtifactAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /artifact/scan
            Method: get
  GuruLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: GuruLayer
      Description: Guru website backend dependencies and common code
      ContentUri: aws/layers/GuruLayer/.
      CompatibleRuntimes:
        - nodejs14.x
      RetentionPolicy: Retain