AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Guru Website Backend API
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs14.x
    Architectures:
      - x86_64
    Role: arn:aws:iam::009678277760:user/GuruAPI

Resources:
  AddArtifact:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: aws/functions/add-artifact
      Handler: add-artifact-fn.handler
      FunctionName: Guru-Add-Artifact
      Description: AWS Lambda function for adding an artifact in the DB
      Layers:
        - !Ref GuruIntDeps
        - !Ref GuruExtDeps
      Events:
        AddArtifactAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /artifact
            Method: post
  DelArtifact:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: aws/functions/del-artifact
      Handler: del-artifact-fn.handler
      FunctionName: Guru-Del-Artifact
      Description: AWS Lambda function for adding an deleting in the DB
      Layers:
        - !Ref GuruIntDeps
        - !Ref GuruExtDeps
      Events:
        AddArtifactAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /artifact/{id}
            Method: delete
  GetArtifact:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: aws/functions/get-artifact
      Handler: get-artifact-fn.handler
      FunctionName: Guru-Get-Artifact
      Description: AWS Lambda function for fetching an artifact from the DB
      Layers:
        - !Ref GuruIntDeps
        - !Ref GuruExtDeps
      Events:
        AddArtifactAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /artifact/get
            Method: post
  UpdArtifact:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: aws/functions/upd-artifact
      Handler: upd-artifact-fn.handler
      FunctionName: Guru-Upd-Artifact
      Description: AWS Lambda function for upding an artifact in the DB
      Layers:
        - !Ref GuruIntDeps
        - !Ref GuruExtDeps
      Events:
        AddArtifactAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /artifact/{id}
            Method: patch
  GuruIntDeps:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: GuruIntDeps
      Description: Guru website backend internal dependencies
      ContentUri: aws/layers/GuruIntDeps/.
      CompatibleRuntimes:
        - nodejs14.x
      RetentionPolicy: Retain
  GuruExtDeps:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: GuruExtDeps
      Description: Guru website backend external dependencies
      ContentUri: aws/layers/GuruExtDeps/.
      CompatibleRuntimes:
        - nodejs14.x
      RetentionPolicy: Retain
